const assert = require('node:assert/strict');
const {presentation, transcriptForSave} = require('../dist/js/citation-text.js');
const {sourceCaption,configureCaptionLabels} = require('../dist/js/citation-text.js');
configureCaptionLabels(require('../dist/source-caption-labels.json'));
const sourceSegment={type:'quran',source:{surah:18,ayah:30,title:'الكهف، الآية 30'}};
assert.equal(sourceCaption(sourceSegment),'Surah Al-Kahf (18:30) · Translation of Quranic meanings');
assert.equal(sourceCaption({...sourceSegment,source_caption:'Al-Kahf 18:30'}),'Al-Kahf 18:30');
assert.equal(sourceCaption({...sourceSegment,source_caption:''}),'');
assert.equal(sourceCaption({...sourceSegment,source_caption:'Custom'},true),'Surah Al-Kahf (18:30) · Translation of Quranic meanings');
assert.equal(sourceCaption({type:'speech',source:null,source_caption:'Old source'}),'');

const original = 'ومن أتاني يمشي أتيتوه هرولة';
const canonical = 'ومن أتاني يمشي أتيتُه هَرولةً';
const hadith = {type:'hadith',ar:original,en:'Draft',needs_review:true,source:{arabic:canonical,subtitle_arabic:canonical}};
const before = JSON.stringify(hadith);
assert.equal(presentation(hadith).arabic,canonical);
assert.equal(presentation(hadith).originalArabic,original);
assert.equal(presentation(hadith).fromSource,true);
assert.equal(presentation(hadith).changed,true);
assert.equal(JSON.stringify(hadith),before);
assert.equal(transcriptForSave(hadith,canonical),original);
assert.equal(transcriptForSave(hadith,' '+canonical+' '),original);
assert.equal(transcriptForSave(hadith,'نص مختلف'), 'نص مختلف');

const verse = {type:'quran',ar:'تفريغ خاطئ',source:{partial:true,arabic:'نص الآية كاملة',subtitle_arabic:'جزء الآية الصحيح'}};
assert.equal(presentation(verse).arabic,'جزء الآية الصحيح');
assert.equal(transcriptForSave(verse,'جزء الآية الصحيح'), 'تفريغ خاطئ');
const unaligned = {...verse,source:{partial:true,arabic:'نص الآية كاملة'}};
assert.equal(presentation(unaligned).arabic,unaligned.ar);
assert.equal(presentation(unaligned).fromSource,false);
assert.equal(presentation({...hadith,source:{arabic:canonical}}).arabic,canonical);

const paraphrase = {...hadith,source:{...hadith.source,quotation_mode:'paraphrase'}};
assert.equal(presentation(paraphrase).arabic,original);
assert.equal(presentation(paraphrase).fromSource,false);
assert.equal(transcriptForSave(paraphrase,canonical),canonical);
assert.equal(presentation({type:'speech',ar:original,source:hadith.source}).arabic,original);
assert.equal(presentation({...hadith,source:null}).arabic,original);
assert.equal(presentation({...hadith,source:{}}).fromSource,false);
assert.equal(presentation(undefined).arabic,'');
const {reviewPending}=require('../dist/js/citation-text.js');
const reviewed={...hadith,en:'Source translation',reviewed:true,needs_review:false};
assert.equal(reviewPending(reviewed),false);
assert.equal(reviewPending({...reviewed,reviewed:false}),true);
assert.equal(reviewPending({...reviewed,reviewed:'true'}),true);
assert.equal(reviewPending({...reviewed,en:'  '}),true);
assert.equal(reviewPending({...reviewed,candidate:{kind:'quran'}}),true);
assert.equal(reviewPending({...reviewed,source:{...reviewed.source,partial:true,alignment_status:'needs_selection'}}),true);
assert.equal(reviewPending({...reviewed,source:{...reviewed.source,partial:true,alignment_status:'selected',subtitle_english:'Selected excerpt'}}),false);
console.log('Canonical citation text and edit-save checks passed.');
const {sourceExcerptRange}=require('../dist/js/citation-text.js');
const fullArabic='إِنَّ اللَّهَ يُحِبُّ التَّوَّابِينَ وَيُحِبُّ الْمُتَطَهِّرِينَ';
const partialSegment={type:'quran',ar:'إن الله يحب التوابين',source:{arabic:fullArabic,partial:true,subtitle_arabic:'اللَّهَ يُحِبُّ التَّوَّابِينَ'}};
const range=sourceExcerptRange(partialSegment);
assert.equal(fullArabic.slice(range.start,range.end),'اللَّهَ يُحِبُّ التَّوَّابِينَ');
assert.equal(sourceExcerptRange({...partialSegment,source:{...partialSegment.source,partial:false}}),null);
assert.equal(sourceExcerptRange({...partialSegment,source:{...partialSegment.source,quotation_mode:'paraphrase'}}),null);
assert.equal(sourceExcerptRange({...partialSegment,source:{arabic:'الله يحب الله يحب',partial:true,subtitle_arabic:'الله يحب'}}),null);
assert.equal(sourceExcerptRange({...partialSegment,source:{...partialSegment.source,subtitle_arabic:'كلام آخر'}}),null);

assert.equal(sourceCaption({type:'hadith',source:{attribution:'صحيح مسلم ٢٢٣',grade:'صحيح',translation_status:'sourced'}}),'Sahih Muslim 223 · Sahih (authentic)');
assert.equal(sourceCaption({type:'hadith',source:{url:'https://dorar.net/h/test123',grade:'لم يذكر حكمًا'}}),'Dorar · Hadith test123 · See source for grading · English: machine draft');
